First_Contributions/AProblemOnSticks_TREE2.cpp

The issue #1 A Problem On Sticks has been solved. I have followed the contributions guidelines and made a pull request by creating a new branch from my forked repo. The screenshot of the solved problem is also attached below.

AProblemOnSticks_TREE2 issue#1 solved

---

README.md

Testing Closes #5

---

First_Contributions/Socializing_Game_around_Pizza(BIGPIZA).cpp

Added Socializing Game around Pizza (BIGPIZA) file

---

First_Contributions/ChefAndProxy_PROXYC.cpp

this pull request is for the issue Chef and proxy problem .I have attached the .cpp file in first contribution folder .Please merge my pr. The screenshot of the accepted solution from codechef platform is attached herewith.

Code for Chef and Proxy

---

First_Contributions/CerseiAndHerSoldiers_CERSOL.cpp

Solves #22

---

First_Contributions/MinimumMaximum_MNMX.cpp

C++ code to find out minimum sum of costs of operations needed to convert the array into a single element.

Closes #34

---

First_Contributions/SumofDigits_FLOW006.cpp

I have completed the Sum of Digits (FLOW006) #58 Please find the below screenshot.

Closes #58

---

First_Contributions/ExpectedProduct_EXPTPROD.cpp

Closes #23

---

First_Contributions/KthMaxSubarray_KTHMAX.cpp

Closes #24

---

First_Contributions/MaximizeWalkTree_DEMTREE.cpp

MaximizeWalkTree_DEMTREE

---

First_Contributions/NumberMirror_START01.c
README.md

Completed Number Mirror #67 
Closes #67

Closes #67

---

First_Contributions/First and last digit.cpp

Solved this problem on CodeChef, please let me know if anything else required.

Closed #65 Solved FLOW004 Problem

---

First_Contributions/Tweedle-DeeandTweedle-Dum_TWEED.cpp

Tweedle-Dee and Tweedle-Dum 

---

First_Contributions/CielandABProblem_CIELAB.cpp

Closes issue #75

---

First_Contributions/Maximize_Walk_Value_DEMTREE.cpp

Solved Maximize Walk Value (DEMTREE) | Issue No #84  .

Solved Maximize Walk Value (DEMTREE) problem 

---

First_Contributions/UEFA_Champions_League_ucl.cpp

UEFA Champions League UCL | Issue no #83

Solved UEFA Champions League UCL Problem .

---

First_Contributions/Truth and Dare_TRUEDARE.cpp

Closes #90 (TRUEDARE question from codechef). Please also find the attached submission status link of the code in codechef.
[LINK](https://www.codechef.com/viewsolution/39084646)

Closes #90

---

First_Contributions/LongHomework_LNGHW.cpp

Closes #94

---

First_Contributions/Summation over nCr_SUMNCR.cpp

Closes #93 
Please find the [link](https://www.codechef.com/viewsolution/39088243) of the solution submitted to codechef.

Closes #93

---

First_Contributions/RecruitVillagers_VILLINE.cpp

Closes #91

---

First_Contributions/Change It_CHNGIT.cpp

Closes #92 
Here is the [link](https://www.codechef.com/viewsolution/39088280) to the submission in codechef.

Closes #92

---

First_Contributions/ChefAndHisDailyRoutine_CHEFROUT.cpp

Closes #31
Please find the [link](https://www.codechef.com/viewsolution/39111132) of the sol submitted to codechef

Closes #31

---

First_Contributions/SecretRecipe_CHEFRUN.cpp

Closes #29 
Please find the [link](https://www.codechef.com/viewsolution/39114133) of the sol submitted to codechef

Closes #29

---

First_Contributions/GukiZHasMoreCandies_GHMC.cpp

Closes #21 
Please find the [link](https://www.codechef.com/viewsolution/39129461) of the sol submitted to codechef

Closes #21
